### ISSUE TITLE
VondUI's XIVAuras but it is in 1080p and slightly altered

### ISSUE THREAD

**Issue by Otkar** [gingertonik/plugin-export-strings#2]
It has all jobs, some are more altered than others.

[Ghostbin link](https://www.klgrth.io/paste/m4v8e)

**Comment by gingertonik** [comment]
added https://github.com/gingertonik/plugin-export-strings/blob/main/XIVAuras/VondUI's%20XIVAuras%20but%20it%20is%20in%201080p%20and%20slightly%20altered
